{% set name = "asttrs" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asttrs-{{ version }}.tar.gz
  sha256: e60d02cd336b72fa22882629efbb22526663f4ef9c868ae13266c293a383e660

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
    - poetry
  run:
    - python >=3.7,<3.11
    - astor
    - attrs
    - black
    - cattrs
    - isort

test:
  imports:
    - asttrs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ryanchao2012/asttrs
  summary: A attrs-style wrapper for python ast
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
